import os
import sqlite3
from datetime import datetime

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:
    psycopg = None
    dict_row = None

BASE_DIR = os.path.dirname(__file__)
SQLITE_PATH = os.path.join(BASE_DIR, "olympic.db")
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
ON_RENDER = bool(os.environ.get("RENDER") or os.environ.get("RENDER_SERVICE_NAME"))

if ON_RENDER and not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL chưa được cấu hình. V4 cố ý không dùng SQLite trên Render để tránh mất dữ liệu khi redeploy."
    )

IS_POSTGRES = bool(DATABASE_URL)


def _pg_url():
    url = DATABASE_URL
    if not url:
        return url
    if "sslmode=" not in url:
        url += ("&" if "?" in url else "?") + "sslmode=require"
    return url


class CursorWrap:
    def __init__(self, cursor):
        self.cursor = cursor

    def fetchone(self):
        return self.cursor.fetchone()

    def fetchall(self):
        return self.cursor.fetchall()

    @property
    def rowcount(self):
        return self.cursor.rowcount


class ConnectionWrap:
    def __init__(self, raw, postgres=False):
        self.raw = raw
        self.postgres = postgres

    def _sql(self, sql):
        return sql.replace("?", "%s") if self.postgres else sql

    def execute(self, sql, params=()):
        if self.postgres:
            cur = self.raw.cursor()
            cur.execute(self._sql(sql), params)
            return CursorWrap(cur)
        return CursorWrap(self.raw.execute(sql, params))

    def executescript(self, script):
        if self.postgres:
            cur = self.raw.cursor()
            for statement in script.split(";"):
                statement = statement.strip()
                if statement:
                    cur.execute(statement)
            return CursorWrap(cur)
        self.raw.executescript(script)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()


def db():
    if IS_POSTGRES:
        if psycopg is None:
            raise RuntimeError("Thiếu thư viện psycopg. Hãy chạy pip install -r requirements.txt")
        raw = psycopg.connect(_pg_url(), row_factory=dict_row, connect_timeout=10, prepare_threshold=None)
        return ConnectionWrap(raw, postgres=True)
    raw = sqlite3.connect(SQLITE_PATH)
    raw.row_factory = sqlite3.Row
    raw.execute("PRAGMA foreign_keys=ON")
    return ConnectionWrap(raw, postgres=False)


def backend_name():
    return "PostgreSQL / Supabase" if IS_POSTGRES else "SQLite local"


def init_db(admin_password_hash):
    con = db()
    if IS_POSTGRES:
        con.executescript("""
        CREATE TABLE IF NOT EXISTS users(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'player',
            approved INTEGER NOT NULL DEFAULT 0,
            full_name TEXT,
            dob TEXT,
            gender TEXT,
            class_name TEXT,
            phone TEXT,
            grade_group TEXT,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS rounds(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            description TEXT,
            grade_group TEXT,
            opens_at TEXT,
            closes_at TEXT,
            active INTEGER NOT NULL DEFAULT 1,
            selected_sport TEXT
        );
        CREATE TABLE IF NOT EXISTS questions(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            round_id INTEGER NOT NULL REFERENCES rounds(id) ON DELETE CASCADE,
            game_type TEXT NOT NULL,
            qtype TEXT NOT NULL,
            content TEXT NOT NULL,
            options_json TEXT,
            correct_json TEXT NOT NULL,
            points INTEGER NOT NULL DEFAULT 10,
            explanation TEXT,
            image_data TEXT
        );
        CREATE TABLE IF NOT EXISTS attempts(
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            round_id INTEGER NOT NULL REFERENCES rounds(id) ON DELETE CASCADE,
            score INTEGER NOT NULL DEFAULT 0,
            elapsed_seconds INTEGER NOT NULL DEFAULT 0,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            violations INTEGER NOT NULL DEFAULT 0,
            detail_json TEXT,
            server_score INTEGER NOT NULL DEFAULT 0
        );
        CREATE TABLE IF NOT EXISTS attempt_answers(
            attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
            question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
            score INTEGER NOT NULL DEFAULT 0,
            is_correct INTEGER NOT NULL DEFAULT 0,
            answered_at TEXT NOT NULL,
            PRIMARY KEY(attempt_id, question_id)
        );
        CREATE INDEX IF NOT EXISTS idx_questions_round ON questions(round_id);
        CREATE INDEX IF NOT EXISTS idx_attempts_user_round ON attempts(user_id, round_id);
        CREATE INDEX IF NOT EXISTS idx_attempts_round_finished ON attempts(round_id, finished_at);
        """)
        con.execute("ALTER TABLE rounds ADD COLUMN IF NOT EXISTS selected_sport TEXT")
        con.execute("ALTER TABLE attempts ADD COLUMN IF NOT EXISTS server_score INTEGER NOT NULL DEFAULT 0")
        con.execute("ALTER TABLE questions ADD COLUMN IF NOT EXISTS image_data TEXT")
        con.execute(
            """INSERT INTO users(username,password_hash,role,approved,full_name,created_at)
               VALUES(?,?,?,?,?,?) ON CONFLICT(username) DO NOTHING""",
            ("admin", admin_password_hash, "admin", 1, "Quản trị viên", datetime.now().isoformat(timespec="seconds"))
        )
    else:
        con.executescript("""
        CREATE TABLE IF NOT EXISTS users(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'player',
            approved INTEGER NOT NULL DEFAULT 0,
            full_name TEXT,
            dob TEXT,
            gender TEXT,
            class_name TEXT,
            phone TEXT,
            grade_group TEXT,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS rounds(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            description TEXT,
            grade_group TEXT,
            opens_at TEXT,
            closes_at TEXT,
            active INTEGER NOT NULL DEFAULT 1,
            selected_sport TEXT
        );
        CREATE TABLE IF NOT EXISTS questions(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            round_id INTEGER NOT NULL,
            game_type TEXT NOT NULL,
            qtype TEXT NOT NULL,
            content TEXT NOT NULL,
            options_json TEXT,
            correct_json TEXT NOT NULL,
            points INTEGER NOT NULL DEFAULT 10,
            explanation TEXT,
            image_data TEXT,
            FOREIGN KEY(round_id) REFERENCES rounds(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS attempts(
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER NOT NULL,
            round_id INTEGER NOT NULL,
            score INTEGER NOT NULL DEFAULT 0,
            elapsed_seconds INTEGER NOT NULL DEFAULT 0,
            started_at TEXT NOT NULL,
            finished_at TEXT,
            violations INTEGER NOT NULL DEFAULT 0,
            detail_json TEXT,
            server_score INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(round_id) REFERENCES rounds(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS attempt_answers(
            attempt_id INTEGER NOT NULL,
            question_id INTEGER NOT NULL,
            score INTEGER NOT NULL DEFAULT 0,
            is_correct INTEGER NOT NULL DEFAULT 0,
            answered_at TEXT NOT NULL,
            PRIMARY KEY(attempt_id, question_id),
            FOREIGN KEY(attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
            FOREIGN KEY(question_id) REFERENCES questions(id) ON DELETE CASCADE
        );
        """)
        # Migration cho database local cũ nếu có.
        cols = [row[1] for row in con.raw.execute("PRAGMA table_info(rounds)").fetchall()]
        if "selected_sport" not in cols:
            con.execute("ALTER TABLE rounds ADD COLUMN selected_sport TEXT")
        cols = [row[1] for row in con.raw.execute("PRAGMA table_info(attempts)").fetchall()]
        if "server_score" not in cols:
            con.execute("ALTER TABLE attempts ADD COLUMN server_score INTEGER NOT NULL DEFAULT 0")
        cols = [row[1] for row in con.raw.execute("PRAGMA table_info(questions)").fetchall()]
        if "image_data" not in cols:
            con.execute("ALTER TABLE questions ADD COLUMN image_data TEXT")
        con.execute(
            "INSERT OR IGNORE INTO users(username,password_hash,role,approved,full_name,created_at) VALUES(?,?,?,?,?,?)",
            ("admin", admin_password_hash, "admin", 1, "Quản trị viên", datetime.now().isoformat(timespec="seconds"))
        )
    con.commit()
    con.close()
